import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Provider from "./components/theme-provider";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip"

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const heuvel = localFont({
  src:"./assets/font/Heuvel grotesk.ttf",
  display: "swap",
  variable: "--font-heuvel",
});

const opensauce = localFont({
  src: [
    {
      path: "./assets/font/open sauce.woff2",
      weight: "400",
      style: "normal"
    },
    {
      path: "./assets/font/open sauce bold.woff2",
      weight: "700",
      style: "normal"
    }
  ],
  display: "swap",
  variable: "--font-open",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({  children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", heuvel.variable, opensauce.variable, "font-sans", inter.variable)}
      
    >
      <head>
        <script
          src="https://cdn.databuddy.cc/databuddy.js"
          data-client-id="a61ec3c4-9d1e-4349-81d4-a70a31236005"
          data-track-outgoing-links="true"
          data-track-performance="false"
          crossOrigin="anonymous"
          async
        ></script>
      </head>
        <body>
          <Provider>
          <TooltipProvider>
          {children}
          </TooltipProvider>
          </Provider>
        </body>
    </html>
  );
}
