import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const heuvel = localFont({
  src:"./assets/font/Heuvel grotesk.ttf",
  display: "swap",
  variable: "--font-heuvel",
});

const opensauce = localFont({
  src:"./assets/font/open sauce.woff2",
  display: "swap",
  variable: "--font-open",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${heuvel.variable} ${opensauce.variable} h-full antialiased font-sans`}
    >
      <body>{children}</body>
    </html>
  );
}
